### ISSUE TITLE
Section 'shaketune' is not a valid config section

### ISSUE THREAD

**Issue by Megastrong1** [frap129/OpenQ1#28]
Hi! After installing the firmware it gives the following error, did I do something wrong or is this a feature?
![image](https://github.com/user-attachments/assets/00071c1e-1b5e-4a67-b833-5dab557bbced)

**Comment by deveth0** [comment]
See #20, you need to update all packages first.

**Comment by frap129** [comment]
Like deveth0 said, updating packages should solve this.

**Comment by Megastrong1** [comment]
This doesn't really solve the problem. Only after I commented out [shaketune] did it work. 
![image](https://github.com/user-attachments/assets/1cebdc79-1680-4fec-9618-bf1d609bc627)

**Comment by frap129** [comment]
In the updates section of Fluidd, did you update everything? Disabling shaketune only hides the error

**Comment by Megastrong1** [comment]
I tried to restart using the "RESTART FIRMWARE" button

**Comment by Megastrong1** [comment]
And also "RESTART KLIPPER"

**Comment by Megastrong1** [comment]
I can demonstrate it on video. Perhaps I'm doing something wrong.

**Comment by frap129** [comment]
> I tried to restart using the "RESTART FIRMWARE" button

That does not restart klipper, that restarts the MCU firmware. The only way to restart from Fluid is using the menu button in the top right, then click services, then the circle arrow next to klipper

**Comment by Megastrong1** [comment]
Let me try your method and then it will be clear.

**Comment by frap129** [comment]
> In the web interface, Fluidd performed all updates and Klipper still did not start. I had to copy q1.cfg and add it to the parent directory and comment it out [shaketune]

Copying q1.cfg to the parent directory doesn't do anything. I think when you restarted to apply the new config, you inadvertently restarted and solved your issue already.

**Comment by Megastrong1** [comment]
![image](https://github.com/user-attachments/assets/92f1f461-f9ad-4360-af08-412e33c5d3cf)

In printer.cfg I changed the path

**Comment by Megastrong1** [comment]
https://disk.yandex.ru/i/B9UTcPHtAmaWHg
Here's a video of what it all looks like.

**Comment by frap129** [comment]
If you've updated everything and that is still happening, something must have gone wrong with the update. You can reinstall shaketune by following the instructions here: https://github.com/Frix-x/klippain-shaketune

or, your fix works fine if you dont plan on using shaketune

**Comment by Megastrong1** [comment]
My fix works and that's enough for me. I just decided to immediately notify you that something is broken somewhere.

**Comment by Megastrong1** [comment]
I tried reinstalling and it worked.

**Comment by messschuh** [comment]
i stuck at same issue today. reinstall with `wget -O - https://raw.githubusercontent.com/Frix-x/klippain-shaketune/main/install.sh | bash` solve the problem for now.

**Comment by Megastrong1** [comment]
Thank you!

**Comment by aidan-gibson** [comment]
Confirmed also got this issue on a fresh install

**Comment by frap129** [comment]
> Confirmed also got this issue on a fresh install

Yep, the base image needs to be rebuilt, but the upstream repo mine was based on was rebased, so that requires a bit of rework and testing to do.

**Comment by frap129** [comment]
Leaving this open for visibility to others
